--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期四, 24 十一月, 2016 
--   DBMS       : MySql 
--   -------------------------------------------------- 

CREATE TABLE `SysAccount`
(
	`AccountName` NVARCHAR(64) NOT NULL DEFAULT '' COMMENT '账户名称',
	`AccountPasswordSecret` NVARCHAR(64) NOT NULL DEFAULT '' COMMENT 'SHA1(密码+salt)',
	`Salt` NVARCHAR(16) NOT NULL DEFAULT '' COMMENT '加密盐值',
	`CreateTime` DATETIME(0) NOT NULL DEFAULT now(),
	`UpdateTime` DATETIME(0) NOT NULL DEFAULT now(),
	PRIMARY KEY (`AccountName`)

)  COMMENT='系统表：账户信息表'
;


