--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期四, 24 十一月, 2016 
--   DBMS       : MySql 
--   -------------------------------------------------- 

CREATE TABLE `SysRoleAuth`
(
	`Id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增id',
	`RoleId` BIGINT NOT NULL DEFAULT -1 COMMENT '角色id',
	`AuthKey` NVARCHAR(128) DEFAULT '' COMMENT '权限key',
	`CreateTime` DATETIME(0) NOT NULL DEFAULT now(),
	`UpdateTime` DATETIME(0) NOT NULL DEFAULT now(),
	PRIMARY KEY (`Id`)

)  COMMENT='系统角色具备权限信息表'
;


