--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期四, 24 十一月, 2016 
--   DBMS       : MySql 
--   -------------------------------------------------- 

CREATE TABLE `SysRole`
(
	`Id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长id',
	`Name` NVARCHAR(32) NOT NULL DEFAULT '' COMMENT '角色名称',
	`Desc` NVARCHAR(64) DEFAULT '' COMMENT '角色描述',
	`Enable` BIT(1) NOT NULL COMMENT '是否启用',
	`CreateTime` DATETIME(0) NOT NULL DEFAULT now(),
	`UpdateTime` DATETIME(0) NOT NULL DEFAULT now(),
	PRIMARY KEY (`Id`)

)  COMMENT='系统角色表'
;


