--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期二, 29 十一月, 2016 
--   DBMS       : MySql 
--   -------------------------------------------------- 

CREATE TABLE `SystemParam`
(
	`Id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长id',
	`Category` NVARCHAR(64) NOT NULL DEFAULT '' COMMENT '参数分类。由设置参数的人自己决定',
	`Key` NVARCHAR(64) NOT NULL DEFAULT '' COMMENT '参数名',
	`Value` NVARCHAR(1024) NOT NULL DEFAULT '' COMMENT '参数值',
	`Creator` NVARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建人',
	`Updator` NVARCHAR(64) NOT NULL DEFAULT '' COMMENT '上次修改人账户',
	`CreateTime` DATETIME(0) NOT NULL DEFAULT now(),
	`UpdateTime` DATETIME(0) NOT NULL DEFAULT now(),
	PRIMARY KEY (`Id`),
	UNIQUE `Unique_Category_Key`(`Category`, `Key`)

)  COMMENT='系统参数配置表'
;


